### ISSUE TITLE
Add get_images support for playlists

### ISSUE THREAD

**Issue by pft** [tkem/mopidy-internetarchive#59]
E.g. spotify playlists may have images associated. I don't know about other backends.

They cannot currently be retrieved with `get_images()`. I have no idea how difficult it would be to add support though. Parsing the URI already errors out.

```
ValueError: Could not parse u'spotify:user:accountname:playlist:2BCH....nws1' as a Spotify URI
```

**Comment by tkem** [comment]
@pft: Are you sure this is the right project?

**Comment by pft** [comment]
Ouch, it isn't... sorry.
