### ISSUE TITLE
Archive.org search and browsing broken

### ISSUE THREAD

**Issue by tkem** [tkem/mopidy-internetarchive#65]
Apparently, the 'q' result header parameter was renamed to 'query', which triggers an exception.

**Comment by gerroon** [comment]
I have the same ussye still.



Jan 10 20:49:51 xxxxx mopidy[9616]: ERROR    InternetArchiveBackend backend caused an exception.
Jan 10 20:49:51 xxxxx mopidy[9616]: Traceback (most recent call last):
Jan 10 20:49:51 xxxxx mopidy[9616]:   File "/usr/lib/python2.7/dist-packages/mopidy/core/library.py", line 19, in _backend_error_handling
Jan 10 20:49:51 xxxxx mopidy[9616]:     yield
Jan 10 20:49:51 xxxxx mopidy[9616]:   File "/usr/lib/python2.7/dist-packages/mopidy/core/library.py", line 112, in _browse
Jan 10 20:49:51 xxxxx mopidy[9616]:     result = backend.library.browse(uri).get()
Jan 10 20:49:51 xxxxx mopidy[9616]:   File "/usr/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get
Jan 10 20:49:51 xxxxx mopidy[9616]:     compat.reraise(*self._data['exc_info'])
Jan 10 20:49:51 xxxxx mopidy[9616]:   File "/usr/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise
Jan 10 20:49:51 xxxxx mopidy[9616]:     exec('raise tp, value, tb')
Jan 10 20:49:51 xxxxx mopidy[9616]:   File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
Jan 10 20:49:51 xxxxx mopidy[9616]:     response = self._handle_receive(message)
Jan 10 20:49:51 xxxxx mopidy[9616]:   File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
Jan 10 20:49:51 xxxxx mopidy[9616]:     return callee(*message['args'], **message['kwargs'])
Jan 10 20:49:51 xxxxx mopidy[9616]:   File "/usr/lib/python2.7/dist-packages/mopidy_internetarchive/library.py", line 49, in browse
Jan 10 20:49:51 xxxxx mopidy[9616]:     return self.__browse_root()
Jan 10 20:49:51 xxxxx mopidy[9616]:   File "/usr/lib/python2.7/dist-packages/mopidy_internetarchive/library.py", line 141, in __browse_root
Jan 10 20:49:51 xxxxx mopidy[9616]:     fields=['identifier', 'mediatype', 'title']
Jan 10 20:49:51 xxxxx mopidy[9616]:   File "/usr/lib/python2.7/dist-packages/mopidy_internetarchive/client.py", line 73, in search
Jan 10 20:49:51 xxxxx mopidy[9616]:     return self.SearchResult(response.json())
Jan 10 20:49:51 xxxxx mopidy[9616]:   File "/usr/lib/python2.7/dist-packages/mopidy_internetarchive/client.py", line 87, in __init__
Jan 10 20:49:51 xxxxx mopidy[9616]:     self.query = result['responseHeader']['params']['q']

**Comment by tkem** [comment]
Then you should probably upgrade to the latest version, as detailed here: https://discourse.mopidy.com/t/announcement-mopidy-internetarchive-v2-0-3/1665
