### ISSUE TITLE
search returns nothing

### ISSUE THREAD

**Issue by steckerhalter** [tkem/mopidy-internetarchive#67]
I installed with pip v2.0.2, no matter what I search for, I get no results. Any idea?

**Comment by tkem** [comment]
See https://discourse.mopidy.com/t/announcement-mopidy-internetarchive-v2-0-3/1665

**Comment by steckerhalter** [comment]
ah sorry, typo there, I'm using v2.0.3 already :)

**Comment by steckerhalter** [comment]
I can browse, but the search doesn't work and there's no exception thrown or anything.

**Comment by tkem** [comment]
Cannot reproduce:
```
tkem@cookie:~$ mpc search any Ween
internetarchive:Ween1994-00-00.SpinRadio
internetarchive:Ween2000-08-27
internetarchive:Ween2011-01-26
internetarchive:Ween1991-10-30
internetarchive:Ween2014-06-27.Ghostwheel
internetarchive:ween1990-02-02.sbd
internetarchive:ween1990-04-18
...
```

**Comment by steckerhalter** [comment]
ok, with mpc I get results too. But with Iris and Moped and don't get results for internetarchive, only for the other sources.

**Comment by tkem** [comment]
Search also works with Mopidy Mobile, so I'd say this is probably a client issue.

**Comment by steckerhalter** [comment]
you're right, other web clients work, thanks!
